baseURL = "https://eidpeter.github.io"
languageCode = "en-us"
title = "Peter Eid"
theme="archie"
copyright = "© Peter Eid"

enableRobotsTXT = true

pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

[params]
	mode="toggle"
	useCDN=true
	subtitle = "Hello! I'm Peter Eid, a Lebanese Data Scientist based in Paris, France.<br><br> Welcome to my personal website, where you'll find a blog (where I share random stuff I find interesting, tech-related or not), some of my generative art and creative coding experiments, my data and software engineering portfolio, as well as my detailed profile.<br><br> Feel free to reach out! Worst case, we have an awkward conversation. (I'm really good at those)"
	mathjax = true
	katex = true
	mainSections = ["posts", "projects", "frames"]
	favicon = "❄️"

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
      unsafe = true


[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto://peter.m.eid@outlook.com"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/peter-m-eid"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/eidpeter"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Frames"
url = "/frames"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
